
" Set Indentation Rules

set autoindent
set tabstop=2
set shiftwidth=2
set softtabstop=2

" Set Statusline
set laststatus=2

filetype indent on
set si
set modeline

"Set Line Number

set number
set numberwidth=3

" Guarentee the line/col numbers
set ruler

" Guarentee Syntax Highlighting
filetype plugin on
syntax on

set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
