#!/bin/bash

## Heh...
alias fucking='sudo'

## Dotfiles Alias
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME '

## Bypass alias only checking first word of command, i.e. only seeing 'sudo', by giving 'sudo' an alias
alias sudo='sudo '

## Move ~/.tmux.conf to $XDG_CONFIG_HOME
## Alias not needed? https://github.com/tmux/tmux/issues/142
## Leaving this here for an easy fix if this is platform-specific
## alias tmux='tmux -f "$XDG_CONFIG_HOME"/tmux/config"'


## ls as we cd
function cd {
	builtin cd "$@" && ls -F
}

## Alias for game, TINT, TINT is not Tetris
alias tint="tint -l 1 -n"

## Easier opening of files from terminal
alias open="xdg-open"

## Keep dotfiles when switching users
## TODO: Not Working?? 
alias su="sudo -E su -p"

## TTY Clock, Timer
alias clock="tty-clock"
alias timer="tty-countdown"


## TODO: Check if session is SSH or not before reboot
function reboot {
	echo null
}

